"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var test_1 = require("./test");
var game_1 = require("./game");
var message = "Hello Worlds";
console.log(message);
var newTest = new test_1.Test();
var result = newTest.test();
console.log(result);
var gameRound = new game_1.Game();
var newGameRow = gameRound.createGameRow();
console.log(newGameRow);
